branches:
  only:
    - master

language: cpp
compiler:
  - gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install libglew-dev libpng12-dev libjpeg-dev libpulse-dev libopenexr-dev libxrandr-dev build-essential libsdl2-dev cmake
  - git submodule init
  - git submodule update

script: bash ./appimage/create_appimage.sh
